name: Deploy DEV

on: [workflow_dispatch]

jobs:
  DeployExpressApp:
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Create env file
        run: echo ${{ secrets.BACKEND_ENVFILE }} | base64 --decode > .env

      - run: yarn

      - run: yarn build

      - uses: "google-github-actions/auth@v0"
        with:
          # Credentials stored inside WDCC organisation secrets
          credentials_json: "${{ secrets.TAITAM_GCP_DEPLOYMENT_SA_CREDENTIALS }}"

      - id: "app-engine-deploy"
        uses: "google-github-actions/deploy-appengine@v0"
        with:
          flags: --no-cache
          project_id: wdcc-taitam-dev
          working_directory: .
